function swap()
{
  local tmp=swaptmp.$$
  ln "$1" "$tmp"
  mv "$2" "$1"
  mv "$tmp" "$2"
}

function cdls()
{
  cd "$1"
  ls
}

alias git-dry="git commit --dry-run"
alias git-opush="git push -u origin"
alias git-cob="git checkout branch"

source ${HOME}/.bashrc-specific

